spring:
  datasource:
    url: jdbc:sqlserver://springboottestdb.database.windows.net:1433;database=springboottestdb;user=adminNT@springboottestdb;password=Password123;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminNT
    password: Password123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191